package stucture;

public enum DiffTypeName {
	
	STATEMENT_INSERT,
	STATEMENT_DELETE,
	STATEMENT_UPDATE,
	STATEMENT_PARENT_CHANGE,
	PARAMETER_INSERT,
	PARAMETER_DELETE,
	PARAMETER_RENAMING,
	ADDITIONAL_FUNCTIONALITY,
	REMOVED_FUNCTIONALITY,
	DECREASING_ACCESSIBILITY_CHANGE,
	METHOD_RENAMING,
	
}
