package stucture;

public enum RefactorType {
	
	EXTRACTMETHOD,
	ADDPARAMETER,
	INLINEMETHOD,
	REMOVEPARAMETER,
	RENAMEMETHOD,
	ENCAPSLUATEFIELD,
	INTRODUCEASSERTION,
	REPLACEEXCEPTIONWITHTEST,
	INLINETEMP,
	RENAMEPARAMETER
	
}
